---
# Configure Raspberry Pi
- name: Configure Raspberry Pi
  hosts: all
  remote_user: pi
  pre_tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        groups: users
        append: true
      with_items:
        - matt
        - susan
        - scans
        - scans@
  roles:
#    - common
    - bertvv.samba

  vars:
    samba_netbios_name: PIHOLE
    samba_server_string: 'file server'
    samba_workgroup: JONES-FAMILY
    
#    samba_global_include: global-include.conf

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '

    samba_map_to_guest: Never
    samba_users:
      - name: scans
        password: snacs
      - name: scans@
        password: snacs

    samba_shares_root: /srv/samba
    samba_shares:
      - name: scans
        comment: 'Public share, writeable by all members of group ‘users’'
        public: 'yes'
        write_list: +users
        group: users
        setype: public_content_t
        browseable: 'yes'
      - name: guestshare
        comment: 'Share accessible for guests'
        guest_ok: 'yes'
        writable: 'yes'
        browseable: 'yes'
      
